### ISSUE TITLE
Is there a way to set a field to the current date?

### ISSUE THREAD

**Issue by bluerosegarden** [konodyuk/obsidian-typing#14]
Hello! This as very quickly become one of my all-time favorite plugins for obsidian. However looking through the docs and I couldn't find a way to automatically set a field to the current date, nor documentation on how to include javascript in an OTL file so I could grab it that way. Is this a feature that exists? Thank you so much in advance!

**Comment by konodyuk** [comment]
The following should already work:
```
type A {
    fields {
        date: Date = "today"
    }
}
```
as well as `tomorrow` or `+2w` or something else.

The slight problem is that the feature is not completely ready and you need to additionally press `Enter` or `Cmd+Enter` on that field to seal the rendered value, because otherwise it will save the note with `date :: today` instead of `date :: 2023-11-30`.

**Comment by bluerosegarden** [comment]
Thank you so much!! That's perfect, I can't wait for the update!

Also if I was more familiar with OTL I'd offer to help with the documentation writing hahaha.
